[package]
name = "csrnet-import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn-import = { git = "https://github.com/burn-rs/burn.git", package = "burn-import"}
structopt   = "0.3.26"
